const ISSUES_DB = [{
    "id": "rech9LNccVQwFBvND",
    "name": "⚡ AHU9 Reheat 1 - Hot Water Valve Override",
    "status": "New",
    "assigned": "Duncan Clark",
    "priority": "Urgent",
    "description": "- The hot water valve on this unit has been overridden to 30% which potentially lead to the operation of the boiler plantroom through the weekend.",
    "solution": "- Confirm this was due to a tenancy complaint and update the tenancy notes for Bakers Delight\n- Approve for CIM to remove the overridden hot water valve and allow for automatic control\n- Monitor impact on the boiler system to ensure override operation is prevented.",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "AHU9-1",
    "tenants": "Bakers Delight",
    "benefit": "⚡ Energy",
    "raised": "8/24/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "recxwjRmT7wWJhjOX",
    "name": "⚙️ Chilled Water System DP Sensor Faulty",
    "status": "New",
    "assigned": "Michael Sealey",
    "priority": "Monitor",
    "description": "- The chilled water system DP sensor constantly fluctuates between 0kPa and >40kPa of pressure even though no chilled water pumps are running.\n- This indicates that the sensor is unreliable and should be investigated before chiller operation begins to increase in the next few months.",
    "solution": "- Identify who is able to investigate this pressure sensor.\n- Investigate the reason for this pressure reading and clean/replace sensor to ensure the BMS chilled water system DP is reading correctly (at 0kPa currently)",
    "companyLogo": "https://dl.airtable.com/.attachments/fa50f755629f435557d06cd83c7ef511/c5451676/ScreenShot2020-07-31at5.48.55pm.png",
    "equipment": "CHWS_Common",
    "tenants": "",
    "benefit": "⚙️ System",
    "raised": "8/21/2020",
    "email": "msealey@agcoombs.com.au"
  },
  {
    "id": "rec8JvYWWKskeHOhq",
    "name": "⚙️ Chilled Water System Cycling",
    "status": "New",
    "assigned": "Matt Sharpe",
    "priority": "Maintenance",
    "description": "- The chilled water system and cooling towers have not had any runtime for >3 months (4.5 months) and CIM recommend implementing a few hours of runtime to ensure equipment is maintained.",
    "solution": "- Dale to determine necessity of condenser water pump + cooling tower operation. (waiting on AG Coombs report coming through by 24/08/2020)\n- Matt to implement automatic chilled water system cycling logic to match the required number of weekend runhours.",
    "companyLogo": "https://dl.airtable.com/.attachments/b06c6e1d76d210b4a17b0f8f245ef088/fe5aa38c/Airmaster_AirmasterAus__Twitter",
    "equipment": "CT-Common, CWP-Common, CHWS_Common",
    "tenants": "",
    "benefit": "⚙️ System",
    "raised": "8/21/2020",
    "email": "msharpe@airmaster.com.au"
  },
  {
    "id": "recuQEr79psnT7lzR",
    "name": "🙂 AHU8 Status Enable Mismatch",
    "status": "New",
    "assigned": "Michael Sealey",
    "priority": "Maintenance",
    "description": "- AHU8 is enabled to run but has been representing a null status feedback since Tuesday (18/08/2020)",
    "solution": "- Investigate AHU8 to confirm the status feedback coming into the BMS is correct.\n- Determine the reason for AHU8 not running via the BMS signal (lose wires, network connection, faulty fan)\n- Click the link below when action has been made towards this investigation.",
    "companyLogo": "https://dl.airtable.com/.attachments/fa50f755629f435557d06cd83c7ef511/c5451676/ScreenShot2020-07-31at5.48.55pm.png",
    "equipment": "AHU8",
    "tenants": "Autograph, Commonwealth Bank, Footy Plus More, Hairhouse Warehouse, Jay Jays, Rockmans, Westpac, Therapy Zone",
    "benefit": "🙂 Occupant",
    "raised": "8/21/2020",
    "email": "msealey@agcoombs.com.au"
  },
  {
    "id": "recu3umKhKsdmP9UI",
    "name": "⚡ Overnight Boiler Operation",
    "status": "In Progress",
    "assigned": "Duncan Clark",
    "priority": "Monitor",
    "description": "- Between the Friday the 21st of August and Monday the 24th of August the hot water system ran non-stop to serve a heating call.\n- This heating call was not generated through faulty controllers indicating 100% hot water valve as all AHUs during the overnight operation were at 0%.\n- Dale mentioned that sometimes the heating call will be overridden to ensure the boilers start a bit earlier in the day and was overridden on Friday during the August meeting but was not overridden on Monday when the fault was observed.",
    "solution": "- CIM to manually disable the heating call to ensure after hours operation does not occur on the 24th - 25th.\n- Investigate the early morning data of the 24th of August to check if the heating call was overridden.\n- Update notes to reflect this accidental overnight operation.",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "Boiler 1, Boiler 2",
    "tenants": "",
    "benefit": "⚡ Energy",
    "raised": "8/24/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "reckJAJ0P5jsmr1xp",
    "name": "⚙️ Stage 4 Weekly Maintenance Run-Time",
    "status": "In Progress",
    "assigned": "Duncan Clark",
    "priority": "Maintenance",
    "description": "- Reduced occupancy due to Stage 4 restrictions for next 6 weeks.\n- The zones associated with these units are closed and units have been fully turned off.\n- To ensure the longevity of the equipment over the 6 week lockdown there will be a manual 1 hour runtime per unit per week.",
    "solution": "- Release BMS override for above units for one hour every Wednesday until tenancy return to regular occupancy:\n[x] 12/08/2020\n[ ] 19/08/2020\n[ ] 26/08/2020\n[ ] 02/09/2020\n[ ] 09/09/2020\n[ ] 16/09/2020 [TBC]",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "AHU3, AHU10, AHU-SS2, PAC-06, PAC-17",
    "tenants": "Angus & Coote, Flight Centre, Hi Touch Mobile, Laser Clinics Australia, Lovisa, Noni B, Prouds, Smiggle, Telstra, Typo, Alter It, Asian Food Link, Cignall, KFC, Wendy's, Tazet, Priceline, Foodcourt Centre, Gloria Jeans Coffee->PAC-17",
    "benefit": "⚙️ System",
    "raised": "8/6/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "rec7y4DhcLZOKXQH7",
    "name": "⚙️ Stage 4 Restrictions - Review Essential HVAC Operation",
    "status": "In Progress",
    "assigned": "Duncan Clark",
    "priority": "Urgent",
    "description": "- Due to stage 4 restrictions being rolled out across Melbourne this week there will be a large amount of tenancy closures.\n- Dale L. has already phoned around to each tenancy to confirm their plans on staying open/closing due to the lockdown in a \"Tenants that can trade\" list\n- The objective is to ensure no HVAC equipment operates during this lockdown unnecessarily and the units that must run still are able to maintain appropriate zone conditions. ",
    "solution": "- Review the \"Tenants that can trade\" list and disable units which will have no occupied zones.\n- Ensure that the boilers are still able to enable to provide heating to remaining units that must stay on to serve essential tenancies.\n- Continually monitor updates to the tenancy trading list over the next 2 weeks to adapt to voluntary closures.",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "Building",
    "tenants": "",
    "benefit": "⚙️ System",
    "raised": "8/4/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "recb4q9AJebH8clcb",
    "name": "🙂 AHU5, AHU9-2 and AHUSS1 Low Supply Air Temperature",
    "status": "In Progress",
    "assigned": "Michael Sealey",
    "priority": "Maintenance",
    "description": "- AHU 5, AHU 9 Deli Reheat and AHU SS1 supply air temperature only reaches a maximum delta t of 5C (expected +10C) to the return air temperature when the hot water valves are open 100%\n- This is likely due to dirty hot water coils which has been limiting the heat exchange into the unit",
    "solution": "- Ensure the hot water coils are passing the design hot water flow through the coils when open 100%\n- Clean the coils to disperse any blockages.\n- Monitor to determine improvement in supply air temperature.",
    "companyLogo": "https://dl.airtable.com/.attachments/fa50f755629f435557d06cd83c7ef511/c5451676/ScreenShot2020-07-31at5.48.55pm.png",
    "equipment": "AHU5, AHU9-2, AHU-SS1",
    "tenants": "Bargains Galore, Bradman's, Chirnside Lotteries, Colette by Colette Hayman, Dusk->AHU5, Kearney Shoes, Manchester & More, Oscar Wylee, Poultry & Game->AHU5, Sanity, Terry White Chemmart, Bras N Things, Australia Post, Odyssey Nails",
    "benefit": "🙂 Occupant",
    "raised": "7/17/2020",
    "email": "msealey@agcoombs.com.au"
  },
  {
    "id": "recXHq9OGXDyp0Nwi",
    "name": "⚡ Excessive Boiler Operation",
    "status": "On Hold",
    "assigned": "Matt Sharpe",
    "priority": "Maintenance",
    "description": "- Boilers, SHHWPs and PHHWPs are being enabled to run for extended periods of time due to faulty field controllers representing static 100% hot water valve positions.\n- When 1-2 controllers fall into fault the number of valve above 40% is always true and the average valve position is between 11 - 22%, preventing the heating call from being disabled.",
    "solution": "- Adjust the heating call logic to disable the heating call when the average valve position is under 25% (will be false if only 2 hot water valves are 100% and the rest are closed)\n- Ensure the heating call is disabled when the number of valves above 40% is less than 3.\n",
    "companyLogo": "https://dl.airtable.com/.attachments/b06c6e1d76d210b4a17b0f8f245ef088/fe5aa38c/Airmaster_AirmasterAus__Twitter",
    "equipment": "HWS_Common",
    "tenants": "",
    "benefit": "⚡ Energy",
    "raised": "7/21/2020",
    "email": "msharpe@airmaster.com.au"
  },
  {
    "id": "recaShrP0WKhaETSF",
    "name": "⚙️ PAC-04 & 05 Controllers are Offline",
    "status": "On Hold",
    "assigned": "Dale Lecluse",
    "priority": "Maintenance",
    "description": "- PAC-04 has gone offline and is currently not being represented on the BMS (6/06/2020)\n- PAC-05 has gone offline and is currently not being represented on the BMS (28/6/2020)\n",
    "solution": "- Reset the units controllers and ensure the graphics on the BMS update to the current sensor readings",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "PAC-05, PAC-04",
    "tenants": "Foodcourt West, Foodcourt Seafood, Poultry & Game->PAC-04, Rainbow Meats",
    "benefit": "⚙️ System",
    "raised": "7/17/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "recKMr1JYUlG148zE",
    "name": "🙂 AHU6 - Poor Temperature Control",
    "status": "On Hold",
    "assigned": "Matt Sharpe",
    "priority": "Maintenance",
    "description": "- AHU 6 is in HVAC mode \"Cool Heat & Free Cooling\" but does not modulate the hot water valve to control temperature.\n- Unit appears to still be in ventilation mode from late April when COVID-19 strategies were deployed.",
    "solution": "- Ensure the HVAC Mode has been reverted to normal heating, cooling and free cooling control\n- Confirm the hot water valve opens to match the heating demand of the unit.",
    "companyLogo": "https://dl.airtable.com/.attachments/b06c6e1d76d210b4a17b0f8f245ef088/fe5aa38c/Airmaster_AirmasterAus__Twitter",
    "equipment": "AHU6",
    "tenants": "Bank of Melbourne->AHU6",
    "benefit": "🙂 Occupant",
    "raised": "7/17/2020",
    "email": "msharpe@airmaster.com.au"
  },
  {
    "id": "recHFg55j3iCZAaha",
    "name": "⚙️ Fire Smoke Exhaust Fans - Offline",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Urgent",
    "description": "- Smoke Exhaust Fans indicate that they are offline.\n- This could lead to a major issues in terms of compliance.",
    "solution": "- Ensure the smoke exhaust fans are available to be enabled in the case of a fire or fire test.",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "Building",
    "tenants": "",
    "benefit": "⚙️ System",
    "raised": "8/21/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "rec8eyj5BX8W9uzJT",
    "name": "⚡ AHU Time Schedule Review - Stage 4 Period",
    "status": "Resolved",
    "assigned": "Duncan Clark",
    "priority": "Maintenance",
    "description": "- Under stage 4 restrictions Victorian sites have been taking an aggressive approach to HVAC, often preventing unit operation from 3pm onwards.\n- Weekend time schedules at Chirnside are also identical to Monday - Friday times and can often be adjusted to start an hour later and end an hour early.",
    "solution": "- CIM to implment time schedule changes to ensure HVAC only runs at the essential times of day.",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "AHU4, AHU5, AHU6, AHU7, AHU10, AHU-SS1, AHU-SS2, AHU-SS3",
    "tenants": "Bupa Optical, Eloquence Homewares, Robin's Kitchen, SNS Exclusive Salon, Bargains Galore, Bradman's, Chirnside Lotteries, Colette by Colette Hayman, Dusk->AHU5, Kearney Shoes, Manchester & More, Oscar Wylee, Poultry & Game->AHU5, Sanity, Terry White Chemmart, Bank of Melbourne->AHU6, Chemist Warehouse, Cookware Brands, Essential Beauty, Hearing Life, Koto Yakitori House, King of the Pack, Michael Hill, OPSM, Radiant Jewellers, Spendless Shoes, Walk Up Cuts and Colours, Alter It, Asian Food Link, Cignall, KFC, Wendy's, Tazet, Australia Post, Odyssey Nails, Priceline, Home Sweet Home, Jamaica Blue",
    "benefit": "⚡ Energy",
    "raised": "8/21/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "rec4UD2F805xKg5AO",
    "name": "⚡ Lighting Schedule Revision",
    "status": "Resolved",
    "assigned": "Duncan Clark",
    "priority": "Maintenance",
    "description": "- Many external and internal lighting schedules either turn on too early or still operate under Thursday-Friday night late trade.\n- CIM propose revising the lighting schedules of the highlighted zones to ensure Chirnside is as close to baseline as possible during the Stage 4 restrictions.",
    "solution": "- Dale to approve of lighting changes recommendations\n- CIM (Duncan) to implement the agreed upon changes:\n    - HDB1 - Foodcourt: 7am - 10pm Thursday/Fridays (8pm close on others)\n    - HDB2 - Centre Court: 6:45am - 10:30pm (7 days a week)\n    - HDB4 - Carpark Lights: Off at 1am (10pm recommend)\n    - HDB5 - Loading Dock: Average 19.5h/day runtime\n    - HDB5 - External Lights: Off at 11pm (10pm recommend)\n    - HDB6 - External Carpark: Off at Midnight (10pm recommend)",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "Building",
    "tenants": "",
    "benefit": "⚡ Energy",
    "raised": "8/21/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "reciArxyXw8caxUhi",
    "name": "⚡ AHU5 Controller Offline",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Urgent",
    "description": "- AHU5 still reading offline after CIM checked it following reset at noon 21 July 2020\n- AHU5 went offline on 17 July which caused the Boiler to run for 24 hours over weekend\n",
    "solution": "- Dale LeCluse to reset controller",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "AHU5",
    "tenants": "Bargains Galore, Bradman's, Chirnside Lotteries, Colette by Colette Hayman, Dusk->AHU5, Kearney Shoes, Manchester & More, Oscar Wylee, Poultry & Game->AHU5, Sanity, Terry White Chemmart",
    "benefit": "⚡ Energy",
    "raised": "7/21/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "recTSVHd1ltho6hsJ",
    "name": "⚙️ AHU7 High Supply Air Flow",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Maintenance",
    "description": "- AHU7 has been reading a high velocity airflow of between 19.0 - 20.0 ls, 24 hours a day\n- This has lead to a high airflow alarm and gives a constant status feedback to the BMS that the units is on",
    "solution": "- Investigate the unit to ensure the unit is not actually running out of hours, (schedule is set to begin at 7:30am and end at 5:00pm but can be deleted temporarily to test the unit)\n- Calibrate or replace the pressure tubes and ensure the airflow is being correctly represented by the BMS",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "AHU7",
    "tenants": "Chemist Warehouse, Cookware Brands, Essential Beauty, Hearing Life, Koto Yakitori House, King of the Pack, Michael Hill, OPSM, Radiant Jewellers, Spendless Shoes, Walk Up Cuts and Colours",
    "benefit": "⚙️ System",
    "raised": "7/17/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "recN7Bqh3QP0iBEXF",
    "name": "⚡ AHU8 controller has gone offline",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Maintenance",
    "description": "- AHU8 has gone offline and the controller needs to be reset\n",
    "solution": "- Reset controller and ensure graphics update on the BMS, if not then escalated further to CIM.",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "AHU8",
    "tenants": "Autograph, Commonwealth Bank, Footy Plus More, Hairhouse Warehouse, Jay Jays, Rockmans, Westpac, Therapy Zone",
    "benefit": "⚡ Energy",
    "raised": "7/3/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "recpsyXzIMwnnpcng",
    "name": "⚙️ Multiple AHU Critical Equipment Failure",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Urgent",
    "description": "- AHU operation failure (online but not receiving power) likely caused by power surge on 30 June 2020\n- AHU equipment failure has caused Boiler to stop heating building due to limited heating calls",
    "solution": "- Instruct AG Coombes to reset switchboard or units",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "AHU-SS1, AHU-SS3, AHU8, AHU9, AHU10",
    "tenants": "Australia Post, Odyssey Nails, Home Sweet Home, Jamaica Blue, Autograph, Commonwealth Bank, Footy Plus More, Hairhouse Warehouse, Jay Jays, Rockmans, Westpac, Therapy Zone, Chirnside Health & Wellbeing, Cotton On, Gloria Jeans Coffee->AHU9, Alter It, Asian Food Link, Cignall, KFC, Wendy's, Tazet",
    "benefit": "⚙️ System",
    "raised": "7/2/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "reczSfxcnHK47Vu7C",
    "name": "⚡ AHU4 controller has gone offline",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Urgent",
    "description": "- AHU4 has gone offline and the controller needs to be reset",
    "solution": "- Reset controller and see if back online. If not escalate to CIM",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "AHU4",
    "tenants": "Big Barber Delux, Connor, Dusk->AHU4, EB Games, Hollywood Nails, Just Jeans, Katies, Maxicare Beauty Salon, Optus, Specsavers, YD., Vodafone",
    "benefit": "⚡ Energy",
    "raised": "6/30/2020",
    "email": "dale.lecluse@gpt.com.au"
  },
  {
    "id": "reciixj2ZoQ1Vx2i1",
    "name": "⚡ SHWP - Excessive Operation",
    "status": "Resolved",
    "assigned": "Duncan Clark",
    "priority": "Maintenance",
    "description": "- The secondary hot water system is currently running 2 pumps when realistically it can get away with running only 1",
    "solution": "- Authorise CIM to lower the system DP setpoint from 150kPa to 120kPa as a first step to prevent excessive operation",
    "companyLogo": "https://dl.airtable.com/.attachments/109d5ff9630bc775ebc23a68ed9ef7c7/2f303f40/ScreenShot2020-07-31at3.56.57pm.png",
    "equipment": "SHWP1, SHWP2",
    "tenants": "",
    "benefit": "⚡ Energy",
    "raised": "6/26/2020",
    "email": "duncan.clark@cim.io"
  },
  {
    "id": "recsraBJLNRHIhhD0",
    "name": "⚡ PAC-05 - 24 Hour Operation",
    "status": "Resolved",
    "assigned": "Dale Lecluse",
    "priority": "Maintenance",
    "description": "- The compressors for this foodcourt unit are being enabled independently of the time scheduled hours of the unit. \n- Will often have several days of heating provided to a low food traffic zone",
    "solution": "- Mech contractor or operations manager to inspect switchboard and investigate why compressors are being excessively enabled. May be due to manual override switch having been turned on",
    "companyLogo": "https://dl.airtable.com/.attachments/79d167632247e825e53b2b4f8b5f2970/8acb7eb1/ScreenShot2020-07-31at3.59.12pm.png",
    "equipment": "PAC-05",
    "tenants": "Foodcourt West",
    "benefit": "⚡ Energy",
    "raised": "6/26/2020",
    "email": "dale.lecluse@gpt.com.au"
  }
]

export default ISSUES_DB